FROM alpine AS builder
WORKDIR /app

RUN apk add --update nodejs=12.22.12-r0 --repository=http://dl-cdn.alpinelinux.org/alpine/v3.12/main
RUN apk add --update npm=12.22.12-r0 --repository=http://dl-cdn.alpinelinux.org/alpine/v3.12/main
RUN npm i -g yarn

COPY . .
RUN yarn install --frozen-lockfile

CMD [ "yarn","--cwd", "api", "prod:start" ]
